posix_cpu_timer: Check cpu_clock_sample() return value
There is probably some high level guarantee that cpu_clock_sample()
won't return an error here, but just in case, and to resolve the
warning, ditch the timer when it returns an error.

This fixes the following warning:
../kernel/time/posix-cpu-timers.c: In function 'posix_cpu_timer_schedule':
../kernel/time/posix-cpu-timers.c:1061:3: error: 'now' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1061 |   bump_cpu_timer(timer, now);

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>
[yaro: 4.14 doesn't have an out label]
Signed-off-by: Yaroslav Furman <yaro330@gmail.com>
Signed-off-by: rezaadi0105 <rezaadipangestu5@gmail.com>